name: Run Insta Crawler

on:
  schedule:
    - cron: '0 16 * * *' # 5분마다 실행 (GitHub의 최소 간격)
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install dependencies
        run: npm install

      - name: Install Supabase
        run: npm install @supabase/supabase-js

      - name: Run crawler
        run: node src/app/api/test/crawler.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          INSTAGRAM_ID: ${{ secrets.INSTAGRAM_ID }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
